import numpy as np
from warnings import warn


def customize_cmap(vmin, vmax, vsep, cmin, cmax, csep):
    from matplotlib.colors import LinearSegmentedColormap
    sep = (vsep - vmin) / (vmax - vmin)
    cdict = {'red': [[0.0, cmin[0], cmin[0]],
                     [sep, csep[0], csep[0]],
                     [1.0, cmax[0], cmax[0]]],
             'green': [[0.0, cmin[1], cmin[1]],
                       [sep, csep[1], csep[1]],
                       [1.0, cmax[1], cmax[1]]],
             'blue': [[0.0, cmin[2], cmin[2]],
                      [sep, csep[2], csep[2]],
                      [1.0, cmax[2], cmax[2]]]}
    return LinearSegmentedColormap('testCmap', segmentdata=cdict, N=256)


def draw_colormap(cmap):
    import matplotlib.pyplot as plt
    x = np.linspace(0, 1, 256)
    x = np.vstack((x, x))
    plt.imshow(x, aspect='auto', cmap=cmap)
    plt.xticks([])
    plt.yticks([])
    for spine in plt.gca().spines.values():
        spine.set_visible(False)
    plt.tight_layout()
    plt.show()


def draw_colorbar_segmented(vmin, vmax, cmap_name, N, location=None, ticks=None):
    import matplotlib.pyplot as plt
    import matplotlib as mpl
    mpl.rcParams['svg.fonttype'] = 'none'
    cmap = plt.get_cmap(cmap_name, N)
    x = np.linspace(0, 1, 256)
    x = np.vstack((x, x))
    im = plt.imshow(x, aspect='auto', cmap=cmap, vmin=vmin, vmax=vmax)
    cb = plt.colorbar(im, location=location)
    cb.set_ticks(ticks, labels=[])
    plt.gcf().savefig(f'{cmap_name}-segmented.svg')
    plt.show()


def draw_colorbar(vmin, vmax, cmap, location, ticks):
    import matplotlib.pyplot as plt

    x = np.linspace(0, 1, 256)
    x = np.vstack((x, x))
    im = plt.imshow(x, aspect='auto', cmap=cmap, vmin=vmin, vmax=vmax)
    cb = plt.colorbar(im, location=location)
    cb.set_ticks(ticks, labels=[])
    plt.show()


def extract_com(case_name, start, end):
    """
    Extract center of mass from my.log
    """
    path = f'../my_work/results/{case_name}'
    coms = []
    with open(f'{path}/my.log', 'r') as f:
        for line in f:
            if line[0] == 'b':
                com = line.split('(y)')[1].split('(z)')[0]
                coms.append(float(com))
    coms = np.array(coms)
    return coms[start:end]


def extract_ave_stretch(case_name, n_chunk):
    path = f'../my_work/results/{case_name}'
    ave_stretch_all = []
    ave_stretch_current = []
    with open(f'{path}/ave_stretch.log', 'r') as f:
        for row, line in enumerate(f):
            if row == 2:
                break
        for row, line in enumerate(f):
            if row % (n_chunk + 1):
                ave_stretch_current.append(float(line.split(' ')[-1].rstrip()))
            else:
                ave_stretch_all.append(ave_stretch_current)
                ave_stretch_current = []
    return np.array(ave_stretch_all[1:])


def t_spike2array(t_spike: dict, pre=0):
    """
    :param t_spike: dict of t_spike generated by brian2
    :param pre: pre-run time
    :return: numpy.ndarray, the 0th column is t_spike, the 1st column is neuron index
    """
    from brian2.units import ms
    res = np.empty((0, 2))
    for neu_id, val in t_spike.items():
        ids = np.repeat(neu_id, val.size)
        res = np.vstack((res, np.c_[val / ms, ids]))
    res[:, 0] -= pre
    return res


def firing_rate(query_ts, spike_ts, sigma=0.05):
    """
    :param query_ts: 1d array
    :param spike_ts: 1d array
    :param sigma: bandwidth of gaussian kernel
    :return: firing rate with the same shape as query_ts
    """
    # time_diff matrix
    time_diff = query_ts[:, np.newaxis] - spike_ts
    # compute the gaussian kernel
    coeff = 1 / (sigma * np.sqrt(2 * np.pi))
    kernel_values = coeff * np.exp(-time_diff ** 2 / (2 * sigma ** 2))
    # sum at every query_time
    return np.sum(kernel_values, axis=1)


if __name__ == '__main__':
    # vmin, vmax, vsep = -0.41, 0.2, 0
    # cmax = np.array([70, 130, 180]) / 256
    # cmin = np.array([139, 0, 0]) / 256
    # draw_colormap(customize_cmap(vmin, vmax, vsep, cmin, cmax, csep=np.array([1., 1., 1.])))
    # draw_colorbar(0, 8, 'plasma', 'bottom', ticks=[0, 2, 4, 6, 8])
    draw_colorbar_segmented(0, 7, 'cividis', 7, ticks=np.arange(7) + 0.5)
